version: '3'
services:
  web:
    image: smutdose/phoenix
    command: mix phx.server
    depends_on:
    - db
    ports:
    - "4000:4000"
    volumes:
    - .:/opt/app
    working_dir: /opt/app
  db:
    image: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
